### ISSUE TITLE
Version 59.v867a10f71ffd unable to connect to Hetzner nodes in Jenkins 2.246.2

### ISSUE THREAD

**Issue by sandrinr** [jenkinsci/hetzner-cloud-plugin#46]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.346.2
OS: Linux - 5.4.0-66-generic
---
ace-editor:1.1
analysis-model-api:10.13.0
ansicolor:1.0.2
ant:475.vf34069fef73c
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
blueocean:1.25.5
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.5
blueocean-commons:1.25.5
blueocean-config:1.25.5
blueocean-core-js:1.25.5
blueocean-dashboard:1.25.5
blueocean-display-url:2.4.1
blueocean-events:1.25.5
blueocean-git-pipeline:1.25.5
blueocean-github-pipeline:1.25.5
blueocean-i18n:1.25.5
blueocean-jira:1.25.5
blueocean-jwt:1.25.5
blueocean-personalization:1.25.5
blueocean-pipeline-api-impl:1.25.5
blueocean-pipeline-editor:1.25.5
blueocean-pipeline-scm-api:1.25.5
blueocean-rest:1.25.5
blueocean-rest-impl:1.25.5
blueocean-web:1.25.5
bootstrap4-api:4.6.0-5
bootstrap5-api:5.1.3-7
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-blocker-plugin:1.7.8
build-monitor-plugin:1.13+build.202205140447
build-timeout:1.21
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
categorized-view:1.12
checks-api:1.7.4
claim:2.18.2
cloud-stats:0.27
cloudbees-bitbucket-branch-source:784.v7fcdc7c670f6
cloudbees-folder:6.729.v2b_9d1a_74d673
cobertura:1.17
code-coverage-api:3.0.4
command-launcher:84.v4a_97f2027398
conditional-buildstep:1.4.2
config-file-provider:3.11.1
copyartifact:1.46.4
credentials:1139.veb_9579fca_33b_
credentials-binding:523.vd859a_4b_122e6
dark-theme:185.v276b_5a_8966a_e
dashboard-view:2.447.vda_124dd35f11
data-tables-api:1.12.1-2
display-url-api:2.3.6
docker-commons:1.19
docker-compose-build-step:1.0
docker-custom-build-environment:1.7.3
docker-java-api:3.2.13-37.vf3411c9828b9
docker-plugin:1.2.9
docker-slaves:1.0.7
docker-workflow:1.29
downstream-build-cache:1.7
durable-task:496.va67c6f9eefa7
echarts-api:5.3.3-1
email-ext:2.91
envinject-api:1.199.v3ce31253ed13
extended-read-permission:3.2
external-monitor-job:191.v363d0d1efdf8
extra-columns:1.25
favorite:2.4.1
font-awesome-api:6.1.1-1
forensics-api:1.15.1
git:4.11.3
git-client:3.11.0
git-server:1.11
github:1.34.4
github-api:1.303-400.v35c2d8258028
github-branch-source:1677.v731f745ea_0cf
gitlab-api:5.0.1-78.v47a_45b_9f78b_7
gitlab-branch-source:633.ved9984f943da_
gitlab-plugin:1.5.35
gradle:1.39.4
greenballs:1.15.1
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
heavy-job:1.1
hetzner-cloud:53.vb2f31f5270a0
htmlpublisher:1.30
jackson2-api:2.13.3-285.vc03c0256d517
jacoco:3.3.2
jakarta-activation-api:2.0.0-3
jakarta-mail-api:2.0.0-6
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-4
javax-mail-api:1.6.2-7
jaxb:2.3.6-1
jdk-tool:1.5
jenkins-design-language:1.25.5
jersey2-api:2.36-2
jira:3.7.1
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.15-1
job-import-plugin:3.5
jobConfigHistory:1156.v536a_97b_8d649
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-4
jsch:0.1.55.2
junit:1119.1121.vc43d0fc45561
ldap:2.10
lockable-resources:2.16
mailer:435.v79ef3972b_5c7
mapdb-api:1.0.9.0
matrix-auth:3.1.5
matrix-project:772.v494f19991984
maven-plugin:3.19
metrics:4.2.10-389.v93143621b_050
mina-sshd-api-common:2.8.0-36.v8e25ce90d4b_1
mina-sshd-api-core:2.8.0-36.v8e25ce90d4b_1
momentjs:1.1.1
naginator:1.18.1
nodelabelparameter:1.11.0
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.8
parameterized-scheduler:1.0
parameterized-trigger:2.45
pipeline-build-step:2.18
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:598.vcd66b_a_336510
pipeline-input-step:449.v77f0e8b_845c4
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2114.v2654ca_721309
pipeline-model-definition:2.2114.v2654ca_721309
pipeline-model-extensions:2.2114.v2654ca_721309
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2114.v2654ca_721309
pipeline-utility-steps:2.13.0
plain-credentials:1.8
plot:2.1.10
plugin-util-api:2.17.0
popper-api:1.16.1-3
popper2-api:2.11.5-2
postbuildscript:3.1.0-375.v3db_cd92485e1
prism-api:1.28.0-2
promoted-builds:878.v12d3f7937690
publish-over:0.22
pubsub-light:1.16
python:1.3
resource-disposer:0.19
run-condition:1.5
scm-api:616.ve67136f6c77d
script-security:1175.v4b_d517d6db_f0
scriptler:3.5
slack:616.v03b_1e98d13dd
snakeyaml-api:1.30.2-76.vc104f7ce9870
sse-gateway:1.25
ssh-agent:295.v9ca_a_1c7cc3a_a_
ssh-credentials:295.vced876c18eb_4
ssh-slaves:1.821.vd834f8a_c390e
sshd:3.242.va_db_9da_b_26a_c3
structs:324.va_f5d6774f3a_d
subversion:2.15.5
text-finder:1.19
theme-manager:1.4
thinBackup:1.10
throttle-concurrents:2.8
timestamper:1.18
token-macro:308.v4f2b_ed62b_b_16
translation:1.16
trilead-api:1.67.vc3938a_35172f
variant:59.vf075fe829ccb
view-job-filters:2.3
warnings-ng:9.14.0
windows-slaves:1.8.1
workflow-api:1188.v0016b_4f29881
workflow-basic-steps:980.v82219a_ed188e
workflow-cps:2759.v87459c4eea_ca_
workflow-durable-task-step:1199.v02b_9244f8064
workflow-job:1207.ve6191ff089f8
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:833.va_1c71061486b_
ws-cleanup:0.42
yet-another-build-visualizer:1.16
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller: Ubuntu 20.04
Agent: Ubuntu 20.04

### Reproduction steps

1. Install Jenkins 2.246.2 with the Hetzner cloud plugin 59.v867a10f71ffd
2. Run a job that is run on a Hetzner node

### Expected Results

Job is executed on the created Hetzner node.

### Actual Results

Jenkins is able to create the node but unable to connect.

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/4083653/181178626-3d333aa0-3e00-4285-acc1-4c9300963097.png">

The log shows:
```
2022-07-27 06:26:50.425+0000 [id=1005]  WARNING c.d.j.p.hetzner.NodeCallable#call: Connection to 'hcloud-aods4mv97sugj3aj' has failed, remaining retries 4
Also:   java.lang.Throwable: launched here
    at hudson.slaves.SlaveComputer._connect(SlaveComputer.java:287)
    at hudson.model.Computer.connect(Computer.java:445)
    at hudson.slaves.SlaveComputer.tryReconnect(SlaveComputer.java:837)
    at hudson.slaves.RetentionStrategy$Always.check(RetentionStrategy.java:173)
    at hudson.slaves.RetentionStrategy$Always.check(RetentionStrategy.java:161)
    at hudson.slaves.RetentionStrategy.lambda$start$0(RetentionStrategy.java:104)
    at hudson.model.Queue._withLock(Queue.java:1395)
    at hudson.model.Queue.withLock(Queue.java:1269)
    at hudson.slaves.RetentionStrategy.start(RetentionStrategy.java:104)
    at hudson.model.AbstractCIBase.createNewComputerForNode(AbstractCIBase.java:180)
    at hudson.model.AbstractCIBase.updateNewComputer(AbstractCIBase.java:222)
    at jenkins.model.Jenkins.updateNewComputer(Jenkins.java:1666)
    at jenkins.model.Nodes.addNode(Nodes.java:144)
    at jenkins.model.Jenkins.addNode(Jenkins.java:2208)
    at cloud.dnation.jenkins.plugins.hetzner.NodeCallable.call(NodeCallable.java:60)
    at cloud.dnation.jenkins.plugins.hetzner.NodeCallable.call(NodeCallable.java:30)
java.lang.NullPointerException
  at cloud.dnation.jenkins.plugins.hetzner.launcher.HetznerServerComputerLauncher.setupConnection(HetznerServerComputerLauncher.java:149)
  at cloud.dnation.jenkins.plugins.hetzner.launcher.HetznerServerComputerLauncher.launch(HetznerServerComputerLauncher.java:98)
  at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
Caused: java.util.concurrent.ExecutionException
  at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
  at cloud.dnation.jenkins.plugins.hetzner.NodeCallable.call(NodeCallable.java:67)
  at cloud.dnation.jenkins.plugins.hetzner.NodeCallable.call(NodeCallable.java:30)
  at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
  at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:834)
```

### Anything else?

Downgrading to version 53.vb2f31f5270a0 solved the problem.

**Comment by rkosegi** [comment]
Well this is obviously caused by latest feature addition.
Fix is on the way.
