### ISSUE TITLE
Jenkins runner VM is started but does not join Jenkins as a _runner_

### ISSUE THREAD

**Issue by WalBeh** [jenkinsci/hetzner-cloud-plugin#87]
### Jenkins and plugins versions report

  ```text
Jenkins 2.440.1 
Hetzner Cloud Version 87.v3e433a96543b
  ```

### What Operating System are you using (both controller, and any agents involved in the problem)?

` Ubuntu 20.04.6 LTS` controller + agent

### Reproduction steps

1. Start a job with a label configured  for  `Clouds` in jenkins - we have several, but none seems to work. We re using this for several month, on 2024-10-07 we noticed that we do not have enough _dynamic_ runners in Jenkins.
2. A VM is started on Hetzner: Public+Private IP
3. The recently started VM does **not** join Jenkins: Join via SSH (jenkins) user, use private IP first. 

### Expected Results

I would expect that the VM _joins_ Jenkins and executes the started job.

### Actual Results

Although the VM is visible in the Hetzner Console and also in the Jenkins Logs, it is **not* joined to jenkins:

```log
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:678)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:686)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:154)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.java:136)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:223)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at cloud.dnation.hetznerclient.UserAgentInterceptor.intercept(UserAgentInterceptor.java:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at cloud.dnation.hetznerclient.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:38)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at cloud.dnation.jenkins.plugins.hetzner.HetznerCloudResourceManager.createServer(HetznerCloudResourceManager.java:340)
Caused: java.lang.IllegalStateException
	at cloud.dnation.jenkins.plugins.hetzner.HetznerCloudResourceManager.createServer(HetznerCloudResourceManager.java:345)
	at cloud.dnation.jenkins.plugins.hetzner.NodeCallable.call(NodeCallable.java:42)
	at cloud.dnation.jenkins.plugins.hetzner.NodeCallable.call(NodeCallable.java:30)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Oct 07 11:07:09 jenkins-master jenkins[468063]: 2024-10-07 11:07:09.751+0000 [id=49]        INFO        c.d.j.p.hetzner.HetznerCloud#provision: Creating new agent with 1 executors, have 2 running VMs
Oct 07 11:07:09 jenkins-master jenkins[468063]: 2024-10-07 11:07:09.752+0000 [id=49]        WARNING        c.d.j.p.hetzner.HetznerCloud#provision: Cloud capacity reached (0). Has 2 VMs running, but want 1 more executors
Oct 07 11:07:09 jenkins-master jenkins[468063]: 2024-10-07 11:07:09.918+0000 [id=49]        INFO        c.d.j.p.hetzner.HetznerCloud#provision: Creating new agent with 1 executors, have 0 running VMs
Oct 07 11:07:09 jenkins-master jenkins[468063]: 2024-10-07 11:07:09.918+0000 [id=49]        WARNING        c.d.j.p.hetzner.HetznerCloud#provision: Cloud capacity reached (0). Has 0 VMs running, but want 1 more executors
```

Plugin Logs (timestamps do not match, but it looks always the _same_, I think :-) ): 
```
Oct 08, 2024 1:43:54 PM FINE cloud.dnation.jenkins.plugins.hetzner.HetznerCloud provision
provision(cloud=medium-dedicated-runner,label=hetzner,excessWorkload=1)
Oct 08, 2024 1:43:54 PM INFO cloud.dnation.jenkins.plugins.hetzner.HetznerCloud provision
Creating new agent with 1 executors, have 0 running VMs
Oct 08, 2024 1:43:54 PM INFO cloud.dnation.jenkins.plugins.hetzner.HetznerCloudResourceManager searchResourceByLabelExpression
Trying to find single resource for label expression 'jenkins=runner'
Oct 08, 2024 1:43:55 PM FINE cloud.dnation.jenkins.plugins.hetzner.HetznerCloudResourceManager createServer
Calling API to create server resource : class CreateServerRequest {
    automount: null
    datacenter: null
    image: 188918xxx
    labels: {jenkins.io/managed-by=hetzner-jenkins-plugin, jenkins.io/cloud-name=medium-dedicated-runner}
    location: fsn1
    name: hcloud-ebwd2vmgnui8ipvx
    networks: [1259xxx]
    placementGroup: null
    publicNet: class PublicNetRequest {
        enableIpv4: true
        enableIpv6: false
        ipv4: 63286xxx
        ipv6: null
    }
    serverType: cpx31
    sshKeys: [xxx65159-xxxx-46e8-a849-xxxxxxxx]
    startAfterCreate: null
    userData: #cloud-config
    runcmd:
      - tailscale up --authkey=<****> --ssh
    volumes: null
}
Oct 08, 2024 1:44:04 PM FINE cloud.dnation.jenkins.plugins.hetzner.HetznerCloud provision
provision(cloud=medium-dedicated-runner,label=hetzner,excessWorkload=1)
Oct 08, 2024 1:44:04 PM INFO cloud.dnation.jenkins.plugins.hetzner.HetznerCloud provision
Creating new agent with 1 executors, have 1 running VMs
Oct 08, 2024 1:44:04 PM WARNING cloud.dnation.jenkins.plugins.hetzner.HetznerCloud provision
Cloud capacity reached (1). Has 1 VMs running, but want 1 more executors
```

### Anything else?

- We configure the VM with IPv4 public IPs from a _reserved_ pool
- We attach the VM to a private Subnet with sufficient capacity
- Interestingly, even if I set the _Instance CAP_  to `1` the plugin starts at least `2` VMs.
- Creating the VM from the image manually, using the mentioned IPv4 pool IPs and attaching to the private subnet in the Hetzner Console works
- After that I can attach/add this manually created VM to our Jenkins (using the private ip, ssh auth via jenkins user, ignoring SSH key check).

**Comment by rkosegi** [comment]
Hi @WalBeh , thank you for bug report.
Based on conditions you described, it seems this is problem with talking to Hetzner API, which is also confirmed by attached stacktrace.
Unfortunately, there is nothing that this plugin can do about it.

> Interestingly, even if I set the Instance CAP to 1 the plugin starts at least 2 VMs.

oh yes, same thing as in this [bug report](https://github.com/jenkinsci/hetzner-cloud-plugin/issues/85#issuecomment-2310734429), it related to how Hetzner API responds.
